version: 1.0.{build}

clone_depth: 20

cache:
  - C:\Users\appveyor\AppData\Roaming\Racket

build_script:
- '"c:\Program Files (x86)\Microsoft Visual Studio 12.0\vc\vcvarsall.bat" x86'
- echo %cd%
- nmake win32-in-place PKGS="racket-test unstable-flonum-lib net-test"

test_script:
- echo %cd%
- racket\raco.exe pkg show -l
- racket\racket.exe -l tests/racket/test
- racket\racket.exe -l tests/racket/contract/all
- racket\raco.exe test -l tests/json/json
- racket\raco.exe test -l tests/file/main
- racket\raco.exe test -l tests/net/head
- racket\raco.exe test -l tests/net/uri-codec
- racket\raco.exe test -l tests/net/url
- racket\raco.exe test -l tests/net/url-port
- racket\raco.exe test -l tests/net/encoders
- racket\raco.exe test -l tests/openssl/basic
- racket\raco.exe test -l tests/openssl/https
- racket\raco.exe test -l tests/match/main
- racket\raco.exe test -l tests/zo-path
- racket\raco.exe test -l tests/xml/test
- racket\raco.exe test -c tests/stxparse

notifications:
 - provider: Email
   to: 
    - samth@racket-lang.org
   on_build_success: true
   on_build_failure: true

 - provider: Slack
   auth_token:
     secure: VsZxuLzL7f/k5c/UEkiJKYxvNh9ss0Gq5ifwoZl4rlwzgtkU+2bOEo9zaP2FREF5Tb/iw4r7yQXdAYHPeo8GBQ2GQn2IksABPBEUkFrxj1k=
   channel: notifications
