version: 1.0.{build}

clone_depth: 20

cache:
  - C:\Users\appveyor\AppData\Roaming\Racket

build_script:
- '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" x86'
- echo %cd%
- nmake win32-in-place PKGS="racket-test-core"
- nmake win32-base

test_script:
- echo %cd%
- racket\racket.exe -l tests/racket/test

notifications:
 - provider: Email
   to: 
    - samth@racket-lang.org
   on_build_success: true
   on_build_failure: true
