version: 1.0.{build}

clone_depth: 20

cache:
  - C:\Users\appveyor\AppData\Roaming\Racket

build_script:
- '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" x86'
- echo %cd%
- nmake win32-in-place PKGS=""

test_script:
- echo %cd%
- nmake win32-client PKGS=""


notifications:
 - provider: Email
   to: 
    - samth@racket-lang.org
   on_build_success: true
   on_build_failure: true

 - provider: Slack
   auth_token:
     secure: WCMkqS/3iB39INmhzQoZDNJ3zcOXLaRueWvaayOD9MW15DcWrGOAxz7dGrhh/EcQ
   channel: notifications
