name: Snapshot Generation

on:
  push:
    branches:
      - master

jobs:
  create-installer:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - run: |
        git checkout -b github_actions_build_branch___ # have to be on a branch

    - name: Install pkg dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev unzip python libxml2-dev libfindbin-libs-perl make gcc g++ git uuid-dev
    - uses: Bogdanp/setup-racket@v0.7
      with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'regular'
          version: 'current'

    - name: Install s3-sync
      run: |
        sudo raco pkg install -i --auto s3-sync

    - name: Building
      env:
        DISTRO_BUILD_SITE_DEST: "${{ runner.temp }}/site-dest/"
      run: |
        export cpus=$(grep -c ^processor /proc/cpuinfo)
        make snapshot-site PLAIN_RACKET=/usr/bin/racket CONFIG=".github/workflows/site-small.rkt" -j $((cpus+1))

    - name: S3 Sync
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWSAccessKeyID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSecretKey }}
      run: |
        ls -l ${{ runner.temp }}/site-dest/ci-snapshots/
        raco s3-sync --acl public-read --web --redirect-links ${{ runner.temp }}/site-dest/ci-snapshots/ s3://snapshot.racket-lang.org/ci-snapshots/
