name: ARM32 Linux Fast Build

on: [pull_request]

jobs:
  build-racket3m:
    runs-on: [self-hosted, Linux, ARM]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Build Racket 3m
      run: make CPUS=$(nproc) PKGS="" bc-in-place

  build-racketcs:
    runs-on: [self-hosted, Linux, ARM]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Build Racket CS
      run: make CPUS=$(nproc) PKGS="" cs-in-place
